name: hdc_remake
description: Tool to help IDC
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.0.3+1
  path_provider: ^2.0.14
  audioplayers: ^3.0.1
  flutter_launcher_icons: ^0.11.0
  shared_preferences: ^2.1.0
  async: ^2.8.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_hymns.json
    - assets/audio/audioSample.mp3

flutter_icons:
  image_path: "assets/icon/launcherIcon.png"
  android: true
  ios: true